import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { v4 as uuid } from "uuid";
import Button from "../components/core/Button";
import Input from "../components/core/Input";
import Container from "../components/core/Container";
import TaskInput from "../components/task/TaskInput";
import TaskList from "../components/task/TaskList";

const list = [
  {
    id: uuid(),
    name: "Lorem ipsum dolor sit",
    completed: true,
    created: new Date(),
  },
  { id: uuid(), name: "test-2", completed: false, created: new Date() },
  { id: uuid(), name: "test-3", completed: true, created: new Date() },
  { id: uuid(), name: "test-4", completed: false, created: new Date() },
  { id: uuid(), name: "test-5", completed: false, created: new Date() },
];

export default function Home() {
  const [todos, setTodos] = useState(list);

  const addTodo = (value) => {
    const todo = {
      name: value,
      completed: false,
      created: new Date().toISOString(),
    };
    setTodos([{ ...todo, id: uuid() }, ...todos]);
  };

  const markAsCompleted = (id) => {
    setTodos(
      todos.map((todo) => {
        if (todo.id === id) {
          todo.completed = true;
        }
        return todo;
      })
    );
  };

  const deleteTodo = (id) => {
    setTodos(
      todos.filter((todo) => {
        if (todo.id !== id) {
          return todo;
        }
      })
    );
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="App">
          <Container className={styles.addTask}>
            <TaskInput onTodoAdd={addTodo}></TaskInput>
          </Container>
          <div className={styles.taskList}>
            <TaskList
              items={todos}
              onComplete={markAsCompleted}
              onDelete={deleteTodo}
            ></TaskList>
          </div>
        </div>
      </main>
    </div>
  );
}
